### ISSUE TITLE
ligparfen failed

### ISSUE THREAD

**Issue by zhouyu8791** [leelasd/ligpargen#13]
Hi, I want to generate parameter for attached three ligands: MDA, MDB, and MDC. However, Unknown error was reported... Would you help me fix this ?

Thanks !

[MDA.pdb.gz](https://github.com/leelasd/ligpargen/files/1589123/MDA.pdb.gz)
[MDB.pdb.gz](https://github.com/leelasd/ligpargen/files/1589124/MDB.pdb.gz)
[MDC.pdb.gz](https://github.com/leelasd/ligpargen/files/1589125/MDC.pdb.gz)

- [ ] I believe this to be a bug with LigParGen 
- [ ] This is a feature request

## Issue Information
Software name & Version :
Method:

## Actual Behavior

<!--- If suggesting a change/improvement, explain the difference from current behavior —>

**Comment by leelasd** [comment]
@zhouyu8791 Please elaborate more. What net charge did you use?  It works fine for me with charge of -1 but fails with -2 charge. So please check your structures and make sure you are using the right charges (you can use chimera to see what is the net charge on the molecule). 

Hope this helps.

**Comment by zhouyu8791** [comment]
for MDA and MDC, net charge is -1, and for MAB, net charge is -2. However, three were failed for me ...

**Comment by leelasd** [comment]
@Muneeb-Aliyarhussain You have not added the hydrogens to molecule. Please read the paper to know how LigParGen works. Only requirement to make it work is to have an accurate molecule input file, whether its MOL/PDB (hydrogens should be added) or Smiles code. 
Your input seems to have met none of the requirements. So please fix it and upload your input.

**Comment by Muneeb-Aliyarhussain** [comment]
Dear Sir,
             I have tried SMILES .mol and .pdb along with all hydrogens but
I am not getting any result. I will be greatly thankful for this act of
kindness.
thanks.


SMILES.
O(CCCCCCCCCCCCCCCC)c1ccc(C2c3c(O)cc(O)c(C(c4ccc(OCCCCCCCCCCCCCCCC)cc4)c4c(O)cc(O)c(C(c5ccc(OCCCCCCCCCCCCCCCC)cc5)c5c(O)cc(O)c(C(c6ccc(OCCCCCCCCCCCCCCCC)cc6)c6c(O)cc(O)c2c6)c5)c4)c3)cc1

With Best Regards,

*Muneeb Ali,*
*Jr. Research Fellow,*
*Lab No. P-133, Computational Chemistry Unit,*
*Dr. Panjwani Center for Molecular Medicine and Drug Research,*
*International Center for Chemical and Biological Science,*
*The University of Karachi-75270,*
*Karachi-Pakistan*
http://sites.google.com/site/zaheerqasmi/groupmember
