### ISSUE TITLE
Generation of 147 atom molecule fails for unknown reason

### ISSUE THREAD

**Issue by JJchymist** [leelasd/ligpargen#14]
beta-cyclodextrin.pdb (attached gzipped) fails for unknown reason. SMILES cannot be used -- too long.

[beta-cyclodextrin.pdb.gz](https://github.com/leelasd/ligpargen/files/1706808/beta-cyclodextrin.pdb.gz)

**Comment by leelasd** [comment]
@JJchymist maybe it took too much time to process such a big molecule. We have introduced a timeout option. I have generated parameters and they are in the attached zip file. Let me know if there are any other issues. 
[BCD.zip](https://github.com/leelasd/ligpargen/files/1713842/BCD.zip)

**Comment by JJchymist** [comment]
Thank you very much! I'll try it out.





---- On Sun, 11 Feb 2018 00:05:52 +0100 Leela Dodda &lt;notifications@github.com&gt; wrote ----




@JJchymist maybe it took too much time to process such a big molecule. We have introduced a timeout option. I have generated parameters and they are in the attached zip file. Let me know if there are any other issues.

 BCD.zip

**Comment by JJchymist** [comment]
Hi,
sorry to bother you again and to post in a closed issue, but it turned out I'd made a subtle mistake in the previous configuration (however it had no impact on the error). I attach the corrected file 
[conf.pdb.gz](https://github.com/leelasd/ligpargen/files/1732399/conf.pdb.gz)
. Would you be so kind to generate the parameters again? Further, can you provide details on which optimization level etc. has been used?

I would love to be able to use the software locally, so I could generate the parameters myself and not bother anyone;) Can you provide the executables?

Thank you very much in advance and all apologies for posting the addional requests to the thread.
With kind regards
Jan

**Comment by leelasd** [comment]
Dear Jan,

Yeah if you are doing simulations regularly, it would be best for you to request BOSS/LigParGen from Prof. Jorgensen. Email him and CC me with your academic affiliation. 

I used optimization level 0 because it might take for ever to optimizie molecule of this size.
[F6N.zip](https://github.com/leelasd/ligpargen/files/1733764/F6N.zip)

Best wishes,
Leela
