### ISSUE TITLE
OPLS-AA parameters for Asphaltenes and Large PAH type molecules

### ISSUE THREAD

**Issue by MohammedUI** [leelasd/ligpargen#16]
Dear Leela
Thank you for the support. 
I have tried to generate oplsaa parameters for the new structures using the web site but didn't work and the error is unknown.
All of the molecules have zero net charge and they are canonicalised.
Please, can you help by generating oplsaa parameters for the attached structures?
Thanks 
 
[Mohammed structures.tar.gz](https://github.com/leelasd/ligpargen/files/1896287/Mohammed.structures.tar.gz)

- [ ] I believe this to be a bug with LigParGen 
- [ ] This is a feature request

## Issue Information
Software name & Version :
Method:

## Actual Behavior

<!--- If suggesting a change/improvement, explain the difference from current behavior —>

**Comment by leelasd** [comment]
[MK_structures.zip](https://github.com/leelasd/ligpargen/files/1896731/MK_structures.zip)
Here are the Parameter files.

**Comment by MohammedUI** [comment]
Dear Leela,
Thank you very much.
Have a great night
