### ISSUE TITLE
Fail to Generate OPLS Parameters

### ISSUE THREAD

**Issue by SabaAlikhani** [leelasd/ligpargen#19]
Dear Leela, 

I tried to generate the OPLS parameters for my model molecules several times but each time I face the error gate-way time out. The molecule sizes vary from 15 to 212 atoms but even for the 15 atoms
I get the same error. I will really appreciate if you could help to solve this problem. Here is the pdb file of the zero-charged and optimized molecules so I hope you could guide me to find out what is wrong.
[Molecule_Models.zip](https://github.com/leelasd/ligpargen/files/2061760/Molecule_Models.zip)

Thanks in advance

**Comment by SabaAlikhani** [comment]
I really need this and will really appreciate if sb could help me with it...

**Comment by leelasd** [comment]
Why don't you simply have one residue name to all the atoms and assign back residues after the LigParGen calculations

**Comment by SabaAlikhani** [comment]
Thanks for your reply, if you mean to do the calculations for different residues of the molecules, I have already done that, but I wanted to ask if there is a more efficient way. Isn't it possible to do sth with time-out and let the LigParGen do more calculations before failing so soon?

**Comment by leelasd** [comment]
Nope !! I am asking you to edit the PDB such that there is just one PDB id for all the atoms. LigParGen is meant for singe residue organic molecules not for multi-residue systems.

**Comment by SabaAlikhani** [comment]
Ok, thanks anyway
