### ISSUE TITLE
when enter the smiles format for nitrate ion, i.e. [n+](=o)([o-])[o-], errors appeared!

### ISSUE THREAD

**Issue by csu1505110121** [leelasd/ligpargen#20]
- [x] I believe this to be a bug with LigParGen 

## Issue Information
Software name & Version : g
Method:

## Actual Behavior

<!--- If suggesting a change/improvement, explain the difference from current behavior —>

**Comment by leelasd** [comment]
It is an inoganic ion. You are not supposed to use LigParGen/CM1A for something like NO3-
