### ISSUE TITLE
ligpargen error due to more than 200 atoms.

### ISSUE THREAD

**Issue by Muneeb-Aliyarhussain** [leelasd/ligpargen#21]
<!--
My amphiphilic compounds having 224 atoms and I have tried everything but ligpargen showing unknown errors. I need the GROMACS topology (.gro and .itp) files for my compound.
This is the smiles code and PDB file of my compound.
O(CCCCCCCCCCCCCCCC)c1c(OCCCCCCCCCCCCCCCC)ccc(C2=C(O)C(=O)c3c(OCCCCCCCCCCCCCCCC)cc(OCCCCCCCCCCCCCCCC)cc3O2)c1
[muneeb.zip](https://github.com/leelasd/ligpargen/files/2146278/muneeb.zip)

**Comment by leelasd** [comment]
@Muneeb-Aliyarhussain Yes LigParGen is not yet equipped with parameterizing ligands with more than 200 atoms. Its really tough to perform a CM1A AM1 calculation for such a large molecule in a reasonable time.
