### ISSUE TITLE
Unknown Error Generating Parameters for SO4 2-

### ISSUE THREAD

**Issue by Nanundson3** [leelasd/ligpargen#22]
Hello,

I have been using LigParGen to generate OPLS parameters for an organic catalyst I've been using for research, and haven't had any issues, it has been working well. I've been submitting pdb files with optimized geometries and vibrational frequencies from a computational chemistry program called WebMO. 

Now I want to generate parameters for an SO4 2- molecule. I have generated a pdb file the same way from WebMO, but LPG gives me an Unknown error. I have reviewed the file in a text editor, and change the ligand from UNK to SO4, but it still isn't working. I was wondering if you could help me. Thanks!

[sofour.pdb.zip](https://github.com/leelasd/ligpargen/files/2192997/sofour.pdb.zip)

I tried uploading the file as pdb but this doesn't support it, so I've uploaded a zip file in hope that that helps. Please let me know what other information I can provide to help you. Thank you.

**Comment by leelasd** [comment]
Hi @Nanundson3, LigParGen is for organic molecules, it is not currently equipped to deal with ions. They are both very different. One is an organic molecule, where as SO4 -2 is inorganic

**Comment by Nanundson3** [comment]
Ok, thank you very much!
