### ISSUE TITLE
OPLSAA parameters for complexses  

### ISSUE THREAD

**Issue by MohammedUI** [leelasd/ligpargen#23]
Hello all, 
Please, can you help to generate oplsaa parameters for attached structures?
Thanks 
Mohammed
[complexes.zip](https://github.com/leelasd/ligpargen/files/2195249/complexes.zip)

**Comment by leelasd** [comment]
Dear @MohammedUI, 

You should only post the issues here. Please try it yourself. 
If you are sure that there is a problem with the server then please let us know.

**Comment by MohammedUI** [comment]
Dear Leela,
I tried before I post it here and the server didn't work with the structures.
I'm sorry I did not mention that.
Thank you
