### ISSUE TITLE
Atom numbering

### ISSUE THREAD

**Issue by bkpgh** [leelasd/ligpargen#48]
- [ ] I believe this to be a bug with LigParGen 
- [ ] This is a feature request

## Issue Information
Software name & Version :
Method:

## Actual Behavior

<!--- If suggesting a change/improvement, explain the difference from current behavior —>

**Comment by petersbk-git** [comment]
I just wanted to confirm that ligpargen generated .pdb files have atom numbering (e.g. for defining bonds between atoms) starting from "1" while openMM .xml files have atom numbering beginning with "0" (zero). Correct?
