### ISSUE TITLE
Unknown error with some mol files

### ISSUE THREAD

**Issue by matteoaldeghi** [leelasd/ligpargen#7]
- [x] I believe this to be a bug with LigParGen 
- [ ] This is a feature request

I am having some issues with LigParGen being able to read in mol files for a molecule I am trying to parameterise (thiamine diphosphate, net charge of -2).

I generated mol files using a few different programs (attached) from a mol2 file initially made with Maestro (TPP.mol2). When trying to run LigParGen with any of these mol files, I get the error “Found residue ligand UNK. Unknown error. Please check input file.”. The problem might be with reading in the file: if I use the chemical drawer on the website, and paste the same mol file in there (the molecule gets uploaded correctly), then make SMILES from it and run the program, all goes fine and the molecule is indeed parameterised. On the other hand, if I build a test molecule in Maestro (e.g. benzene) and upload its mol file, all goes smoothly, so it doesn’t seem to be a general issue with the mol format written by Maestro.

[mol_files.zip](https://github.com/leelasd/ligpargen/files/1464963/mol_files.zip)

**Comment by leelasd** [comment]
@matteoaldeghi The problem comes from the lack of canonicalization in the molecule. In such cases, making Z-matrix for parameter generation fails.  Please use openbabel to canonicalized the molecule and try it again with Web server. It should work. I tried it and here are the force-field files. 
The atom ordering might have changed but the coordinates remain the same. 

hope this works. 
[TTP.zip](https://github.com/leelasd/ligpargen/files/1464968/TTP.zip)

**Comment by matteoaldeghi** [comment]
@leelasd yes that was it! Thanks!

An idea could be to run openbabel by default on the uploaded files? As I guess this may happen relatively frequently. It would also allow importing other common formats, like mol2 or pdb. Just a thought.

**Comment by leelasd** [comment]
@matteoaldeghi !! Yes, in fact, that's what goes in the server. The main issue is that canonicalization is not a default option as it changes the way atoms are ordered. Some users are not comfortable with it. 
But you are right. It's certainly better to give atom reordered parameter files than  an error. I will include this feature on the server soon.
