### ISSUE TITLE
DPPC alkyl chain length

### ISSUE THREAD

**Issue by Navya321** [leelasd/ligpargen#8]
Problem is with respect to the force field parameters of the lipid bilayer: dppc (Dipalmitoylphosphatidylcholine) molecule.

- [ ] I believe this to be a bug with LigParGen 

## Issue Information
Software name & Version : web service LigParGen

## Expected Behavior
Force field parameters should be available

## Actual Behavior
The opls-aa force field parameters are available when I keep the chain length of the dppc (Dipalmitoylphosphatidylcholine) molecule to 
7 Carbon atoms, however, when I increase it to 14 the service shows error. It pointed me to post the error on this forum. 
It would be great if the authors would fix this error. Also, I feel that the parameters for the alkyl chain CH2 groups won't really change so it shouldn't be a problem if I put 10 Carbon atoms or hundred.
Number of atoms in my molecule is 130 (less than the limit value of 200).

Regards,
Navya
IIT Guwahati
India

**Comment by leelasd** [comment]
This server is not designed for Lipid molecules. You should look at recent publications on OPLS-AA Lipid force fields for that. 
@Navya321  also please attach pdb/mol file, whatever input you used,  to exactly diagnose what the problem is.

**Comment by Navya321** [comment]
Thanks for the quick response. 

Sure, I will sift through the recent publications for the same. I was using the Draw Molecule feature, so there is no pdb/mol file; the molecule was DPPC. 

Further, it would be great if you all can come up with an added tool for lipid force field parameters.

Great work though. 
Cheers.

**Comment by leelasd** [comment]
@Navya321 Sorry Cannot really help if I don't have an input.
Lipid molecules are extremely sensitive to parameterization and need to be carefully crafted, and is beyond the scope of the server.
